palindrome_prod: number_prod.cc number_prod.h palindrome_prod.cc palindrome_prod.h main_palindrome.cc
	g++ number_prod.cc palindrome_prod.cc main_palindrome.cc -o palindrome_prod

clean:
	rm *.o output

